### ISSUE TITLE
Class issue

### ISSUE THREAD

**Issue by ChamoC** [data2health/mtip-tutorial#42]
- [x] Cannot assign
- [ ] Audio keeps cutting off
- [ ] Have to log/off and back on

**Comment by tmdillon** [comment]
**Great** Issue

**Comment by ChamoC** [comment]
Cannot Assign
Cannot Create milestones

**Comment by nicolevasilevsky** [comment]
This is probably because you (lack of) permissions

**Comment by jmcmurry** [comment]
Not sure why you would have had issues with audio, but it may have been a bandwidth issue.
