### ISSUE TITLE
Lesson 4 - quoting in slack?

### ISSUE THREAD

**Issue by hayesb** [data2health/mtip-tutorial#45]
If quoting saves time in slack, add short activity around this. I missed this today and which I had some notes to go back to.

**Comment by jmcmurry** [comment]
I'm not 100% sure I understand the question, but will take a stab: in slack there is threading, so you don't need to quote. Quoting is what can be done on Gitter in the absence of threading feature. When conversations leapfrog, you can quote to show what you're responding to.
