### ISSUE TITLE
How to keep cats off the keyboard

### ISSUE THREAD

**Issue by Bioscibrarian** [data2health/mtip-tutorial#46]
![TokiJune2015](https://user-images.githubusercontent.com/13007103/54946644-8ae25e80-4f06-11e9-8784-e3dbbe2c42d4.jpg)

**Comment by Bioscibrarian** [comment]
Especially when they're sideways...

**Comment by LisaOKeefe1** [comment]
What keyboard?

**Comment by Bioscibrarian** [comment]
![BoboComputes](https://user-images.githubusercontent.com/13007103/54947541-8dde4e80-4f08-11e9-84cc-4cfb309e5844.jpg)

Better? (Couldn't find keyboard photo earlier)

**Comment by LisaOKeefe1** [comment]
What is this lovely cat's name @Bioscibrarian?

**Comment by Bioscibrarian** [comment]
@LisaOKeefe1 , sideways cat is Toki, Boris is the computer monitoring cat.

**Comment by LisaOKeefe1** [comment]
> @LisaOKeefe1 , sideways cat is Toki, Boris is the computer monitoring cat.

I love them both!
