### ISSUE TITLE
clinical data

### ISSUE THREAD

**Issue by richard1933** [data2health/mtip-tutorial#7]
- [x] - extract data from EMR
- [ ] - pre-process raw data

**Comment by richard1933** [comment]
testing

**Comment by nicolevasilevsky** [comment]
@richard1933  you need to have a space between the brackets, in order for it to display properly

**Comment by nicolevasilevsky** [comment]
you can also click the "Preview" tab (next to Write), to see how the markdown will display. I find this super useful. And you can also go back and edit your comment after you have submitted it too.

**Comment by richard1933** [comment]
Nicol,
This is very helpful, thanks!

- Richard

**Comment by jmcmurry** [comment]
@data2health/ops Please look at this
